packages:
  - packages/*

catalogs:
  stack:
    typescript: ^5.9.2
    ts-jest: ^29.4.1
    ts-node: ^10.9.2
    "@jest/globals": ^30.0.5
    "@jest/types": ^30.0.5
    jest: ^30.0.5

  codebase:
    turbo: ^2.5.6
