[package]
name = "dashtree_core"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
name = "dashtree_core"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2", default-features = false, features = ["std"] }
js-sys = "0.3"
